# cols: ['TIMESTAMP', 'BANK_DC_VOLT', 'BANK_DC_CURRENT', 'BANK_SOC', 'MAX_CELL_TEMPERATURE_OF_BANK', 'VOLT_gap', 'OCV_est', 'BATTERY_STATUS_FOR_CHARGE']
# cols: ['time', 'V', 'I', 'SOC', 'T', 'V_gap', 'OCV', 'status']
# cnn, res10, res18, res34, res50, res101, res152, LSTM,  // WRN, mlp, RNN, tranformer
# MSELoss(), L1Loss()

# path
output_dir: "/data/ess/output/State_Estimation/main"
output_name: "/cnn"
site: 'sionyu'


# data
train_batch_size: 32
test_batch_size : 8
num_workers: 0
drop_last: false
loss_fn: 'L1Loss'   # MSELoss(), L1Loss()
seed: 0
  
seconds: 25
input_cols: ['V', 'I', 'T', 'V_gap', 'OCV']
target_col: ['SOC']
BATTERY_STATUS_FOR_CHARGE : 3  #1(rest), 2(charge), 3(discharge)
mask: 'OCV'

split_ratio: [95,5,0]    # train, val, test
task: 'estimation'





# model
model: res10

# parameter
epochs: 200
decay: 0.98

debug: false