apiVersion: 'kubeflow.org/v1beta1'
kind: Experiment
metadata:
  name: fashion-mnist-experiment-3-v2
  namespace: 'space-openess'
  
spec:
  maxTrialCount: 50
  parallelTrialCount: 5
  maxFailedTrialCount: 3
#   resumePolicy: LongRunning

  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - accuracy
      - loss
      - Validation-loss
  algorithm:
    algorithmName: random
    algorithmSettings: []

  parameters:
    - name: '--learning_rate'
      parameterType: double
      feasibleSpace:
        min: '0.0005'
        max: '0.0015'
#         step: '0.001'
    - name: '--dropout_rate'
      parameterType: double
      feasibleSpace:
        min: '0.1'
        max: '0.9'
    - name: '--opt'
      parameterType: int
      feasibleSpace:
        min: '0'
        max: '1'
    - name: '--layer'
      parameterType: int
      feasibleSpace:
        min: '1'
        max: '5'
    - name: '--epoch'
      parameterType: int
      feasibleSpace:
        min: '5'
        max: '15'
    - name: '--act'
      parameterType: categorical
      feasibleSpace:
        list: # relu, sigmoid, softmax, tanh
        - "relu"
        - "sigmoid" 
        - "softmax"         
        - "tanh"
        
  metricsCollectorSpec:
    source:
      filter:
        metricsFormat:
        - "([\\w|-]+)\\s*=\\s*((-?\\d+)(\\.\\d+)?)"
      fileSystemPath:
        path: /var/log/katib/metrics.log
        kind: File
    collector:
      kind: File

  trialTemplate:
    primaryContainerName: random-training-container
    successCondition: status.conditions.#(type=="Complete")#|#(status=="True")#
    failureCondition: status.conditions.#(type=="Failed")#|#(status=="True")#
    retain: false
    trialParameters:
      - name: learning_rate
        reference: '--learning_rate'
        description: 'learning rate for fashion mnist'
      - name: dropout_rate
        reference: '--dropout_rate'
        description: 'dropout rate for fashion mnist'
      - name: opt
        reference: '--opt'
        description: 'optimizer for fashion mnist'
      - name: layer
        reference: '--layer'
        description: 'neuron network layer for fashion mnist'
      - name: epoch
        reference: '--epoch'
        description: 'epoch for neuron network'
      - name: act
        reference: '--act'
        description: 'activation function for fashion mnist'
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: 'false'
          spec:
            containers:
              - name: random-training-container
                image: 192.168.0.180:5000/fairing-job-v2:56C0889D
                command:
                  - python
                  - /app/fashion-mnist-katib-v2.py
                  - '--learning_rate=${trialParameters.learning_rate}'
                  - '--dropout_rate=${trialParameters.dropout_rate}'
                  - '--opt=${trialParameters.opt}'
                  - '--layer=${trialParameters.layer}'
                  - '--epoch=${trialParameters.epoch}'
                  - '--act=${trialParameters.act}'                  
            restartPolicy: Never